import Book from "../models/book.js";
import Vendor from "../models/Vendor.js";
import PurchaseOrder from "../models/PurchaseOrder.js";

export const runProcurementCheck = async () => {
  console.log("[CRON] Running automated inventory replenishment check...");
    try {
      const lowStockBooks = await Book.find({
        $expr: { $lt: ["$stock", "$reorderThreshold"] }
      });

      if (lowStockBooks.length === 0) {
        console.log("[CRON] Inventory levels are healthy.");
        return;
      }

      console.log(`[CRON] Found ${lowStockBooks.length} items below reorder threshold.`);

      // Find a fallback vendor if books don't have a defaultVendor
      const fallbackVendor = await Vendor.findOne({ isActive: true });
      if (!fallbackVendor) {
        console.warn("[CRON] Cannot auto-order: No active vendors found.");
        return;
      }

      // Group low stock books by vendor
      const ordersByVendor = {};
      for (const book of lowStockBooks) {
        const vendorId = book.defaultVendor ? book.defaultVendor.toString() : fallbackVendor._id.toString();
        
        if (!ordersByVendor[vendorId]) {
          ordersByVendor[vendorId] = [];
        }
        
        ordersByVendor[vendorId].push({
          title: book.title,
          quantity: book.reorderQuantity || 5,
          unitPrice: book.replacementCost || 500, // Estimate for PO
          category: book.category || "General"
        });
      }

      // Create a Purchase Order for each vendor group
      for (const [vendorId, items] of Object.entries(ordersByVendor)) {
        const vendor = await Vendor.findById(vendorId);
        if (!vendor) continue;

        const order = new PurchaseOrder({
          vendor: vendor._id,
          vendorName: vendor.name,
          items,
          notes: "Automated replenishment order generated by inventory engine.",
          expectedDelivery: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 days from now
        });

        // The auto-approve engine in the pre/post save hooks or controller logic 
        // usually handles auto-approvals, but since we are bypassing the controller here,
        // we can apply the auto-approval logic directly.
        order.totalAmount = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);

        if (order.totalAmount < 5000) {
           order.status = "approved";
           order.approvedAt = new Date();
           order.approvals = [{
             approver: null, // System
             status: "approved",
             date: new Date()
           }];
           console.log(`[CRON] Auto-approved small PO for vendor ${vendor.name} (Amount: ${order.totalAmount})`);
           // Note: Budget encumbrance logic for cron could be added here if needed,
           // but for simplicity we will just let it be approved. In a full system we'd call a shared service.
        }

        await order.save();
        console.log(`[CRON] Created Draft/Approved PO for vendor ${vendor.name} with ${items.length} items.`);
      }

  } catch (err) {
    console.error("[CRON] Error during inventory replenishment:", err);
  }
};
